sonar.projectKey=DerickNor_C4
sonar.organization=dericknor
sonar.projectName=ReminderApp

sonar.sources=ReminderApp
sonar.exclusions=**/Tests/**,**/*Tests.swift,**/Preview Content/**

# feed hasil SwiftLint ke SonarCloud sebagai external analyzer report
sonar.swift.swiftLint.reportPaths=swiftlint-report.json
